print ("I am writing a paragraph about writing a paragrph")
print ("Because paragraphs are paragraphs on paragraphs,")
print ("This paragraph is technically a paragraph of a paragraph")
print ("Talking about a paragraph talking about a paragraph.")
print ("And somehow this is still 1 paragraph.")